In [1]:
import torch 
import math

D:\ANACONDA\Lib\site-packages\torch\cuda\__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]


In [5]:
device= 'cuda' if torch.cuda.is_available() else 'cpu'

In [11]:
import torch

a = torch.tensor([2.0,3.0], requires_grad=True)
b= torch.tensor([6.0,4.0],requires_grad=True)

f=3*a**3 - b**2
print(f)

tensor([-12.,  65.], grad_fn=<SubBackward0>)


In [15]:

f.backward(gradient=torch.tensor([1,1]))
print(a.grad)
print(b.grad)

tensor([36., 81.])
tensor([-12.,  -8.])


In [21]:

x=torch.tensor(2.0,requires_grad=True)
y=x**2
y.backward()
print(x.grad)

y=x**2
y.backward()
print(x.grad)

tensor(4.)
tensor(8.)


In [29]:
x=torch.tensor(2.0,requires_grad=True)
y=x**3
z=y**2
z=z.detach()
y.backward()
print(x.grad)


tensor(12.)
