In [1]:
import numpy as np

In [5]:
a=np.array([1,2,3,4,5])
b=np.zeros((2,3))
print(a)
print(b)

[1 2 3 4 5]
[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
c=np.arange(5,11)
print(c)

[ 5  6  7  8  9 10]


In [13]:
d=np.linspace(0,100,8)
print(d)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [15]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr.shape)
print(arr.ndim)
print(arr.size)

(3, 3)
2
9


In [19]:
arr = np.array([
    [1,2],
    [3,4]
])

print(arr[:,1:])

[[2]
 [4]]


In [21]:
#Broadcasting
a = np.array([
    [1],
    [2],
    [3]
])
b = np.array([10,20,30])
a + b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])