In [1]:
import torch 
import math

D:\ANACONDA\Lib\site-packages\torch\cuda\__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]


In [3]:
x=torch.ones(2,3)+1
print(x)

tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [31]:
#BROADCASTING IE MULTIPLY VECTORS WHOSE DIMENSIONS DO NOT MTACH
y=torch.rand((1,3),dtype=torch.float64)*10
y=y.to(torch.int32)
print(y)
c=x*y
print(c)

tensor([[3, 9, 9]], dtype=torch.int32)
tensor([[ 6., 18., 18.],
        [ 6., 18., 18.]])


In [33]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(3, 2)  # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a * torch.rand(1, 2)  # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.5282, 0.4285],
         [0.1507, 0.6431],
         [0.9395, 0.8935]],

        [[0.5282, 0.4285],
         [0.1507, 0.6431],
         [0.9395, 0.8935]],

        [[0.5282, 0.4285],
         [0.1507, 0.6431],
         [0.9395, 0.8935]],

        [[0.5282, 0.4285],
         [0.1507, 0.6431],
         [0.9395, 0.8935]]])
tensor([[[0.7331, 0.7331],
         [0.0797, 0.0797],
         [0.9185, 0.9185]],

        [[0.7331, 0.7331],
         [0.0797, 0.0797],
         [0.9185, 0.9185]],

        [[0.7331, 0.7331],
         [0.0797, 0.0797],
         [0.9185, 0.9185]],

        [[0.7331, 0.7331],
         [0.0797, 0.0797],
         [0.9185, 0.9185]]])
tensor([[[0.7688, 0.7011],
         [0.7688, 0.7011],
         [0.7688, 0.7011]],

        [[0.7688, 0.7011],
         [0.7688, 0.7011],
         [0.7688, 0.7011]],

        [[0.7688, 0.7011],
         [0.7688, 0.7011],
         [0.7688, 0.7011]],

        [[0.7688, 0.7011],
         [0.7688, 0.7011],
         [0.7688, 0.7011]]])


In [35]:
#IN PLACE ALTERATION using _
a=torch.tensor([0,math.pi/4,math.pi/2])
a.sin_()
print(a)

tensor([0.0000, 0.7071, 1.0000])


In [37]:
#SEPERATE COPY USIG CLONE
b=a.clone()
print(b)

tensor([0.0000, 0.7071, 1.0000])


In [ ]:
import torch

if torch.cuda.is_available():
    print("CUDA GPU is available!")
else:
    print("CPU only.")

In [43]:
#GPU ACCELERATION USING GPU FOR COMPUTATIONS
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.tensor([1, 2, 3], dtype=torch.float32)

x = x.to(device)

print(x)
print(x.device)

tensor([1., 2., 3.], device='cuda:0')
cuda:0


In [47]:
#tRANSFERIGN OBJECTS IN CPU TO GPU
y=y.to(device)
print(y.device)
c=c.to(device)

cuda:0


UNSQUEEZING
For example, imagine having a model that works on 3 x 226 x 226 images - a 226-pixel square with 3 color channels. When you load and transform it, you’ll get a tensor of shape (3, 226, 226). Your model, though, is expecting input of shape (N, 3, 226, 226), where N is the number of images in the batch. So how do you make a batch of one?

In [51]:
a = torch.rand(3, 226, 226,device=device)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)
print(b.device)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])
cuda:0


let’s say the model’s output is a 20-element vector for each input. You would then expect the output to have shape (N, 20), where N is the number of instances in the input batch. That means that for our single-input batch, we’ll get an output of shape (1, 20).

What if you want to do some non-batched computation with that output - something that’s just expecting a 20-element vector?

In [53]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)


torch.Size([1, 20])
tensor([[0.9687, 0.5915, 0.8608, 0.3055, 0.3374, 0.4203, 0.4455, 0.9707, 0.3872,
         0.5146, 0.7678, 0.9276, 0.7267, 0.4410, 0.0547, 0.3582, 0.9585, 0.5626,
         0.6652, 0.9593]])
torch.Size([20])
tensor([0.9687, 0.5915, 0.8608, 0.3055, 0.3374, 0.4203, 0.4455, 0.9707, 0.3872,
        0.5146, 0.7678, 0.9276, 0.7267, 0.4410, 0.0547, 0.3582, 0.9585, 0.5626,
        0.6652, 0.9593])
torch.Size([2, 2])
torch.Size([2, 2])


In [ ]:
a = torch.ones(4, 3, 2)
b = torch.rand(3)  # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)  # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)  # broadcasting works again!

In [3]:
torch.cuda.device_count()

1

In [5]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 3060 Laptop GPU'